import Head from 'next/head';
import Link from 'next/link';
import toolClusters from '../data/tool_clusters.json';
import industryClusters from '../data/industry_clusters.json';
import useCaseClusters from '../data/use_case_clusters.json';
import materialClusters from '../data/material_clusters.json';
import trustClusters from '../data/trust_clusters.json';
import comparisonClusters from '../data/comparison_clusters.json';
import templateClusters from '../data/template_clusters.json';

function Section({title,items,path,label}){return <section style={{marginTop:30}}><h2>{title}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{items.map(item=><Link key={item.slug || item.tool_url} href={path(item)} style={{border:'1px solid #E5E7EB',borderRadius:16,padding:16,textDecoration:'none',color:'#111827',background:'#fff'}}><strong style={{color:'#065F46'}}>{label(item)}</strong><p style={{color:'#6B7280',marginBottom:0}}>{item.primary_keyword || item.title}</p></Link>)}</div></section>}
export default function Cases(){return <><Head><title>QR Code Cases, Tools, Solutions & Use Cases — BharathQR</title><meta name="description" content="Explore BharathQR cases: QR tools, business solutions, use cases, materials, trust guides, comparisons and printable QR templates."/><link rel="canonical" href="https://bharathqr.com/cases"/><meta property="og:title" content="QR Code Cases, Tools, Solutions & Use Cases — BharathQR" /><meta property="og:description" content="Explore BharathQR cases: QR tools, business solutions, use cases, materials, trust guides, comparisons and printable QR templates." /><meta property="og:url" content="https://bharathqr.com/cases" /><meta name="twitter:title" content="QR Code Cases, Tools, Solutions & Use Cases — BharathQR" /><meta name="twitter:description" content="Explore BharathQR cases: QR tools, business solutions, use cases, materials, trust guides, comparisons and printable QR templates." /></Head><main style={{maxWidth:1100,margin:'0 auto',padding:'2rem 1rem'}}><section style={{textAlign:'center',background:'linear-gradient(135deg,#ECFDF5,#FFFFFF)',border:'1px solid #D1FAE5',borderRadius:24,padding:'clamp(1.25rem,5vw,2.5rem)'}}><p style={{color:'#1D9E75',fontWeight:800}}>BharathQR Directory</p><h1 style={{fontSize:'clamp(2rem,6vw,3rem)',margin:'0.25rem 0'}}>QR Code Cases for Indian Businesses</h1><p style={{color:'#4B5563',fontSize:18,lineHeight:1.6}}>Find QR tools, solutions, use cases, print materials, safety guides, comparisons and templates in one place.</p></section><Section title="Tools" items={Object.values(toolClusters)} path={(i)=>i.tool_url} label={(i)=>i.title}/><Section title="Solutions" items={Object.values(industryClusters)} path={(i)=>`/solutions/${i.slug}`} label={(i)=>i.title}/><Section title="Use Cases" items={Object.values(useCaseClusters)} path={(i)=>`/use-cases/${i.slug}`} label={(i)=>i.title}/><Section title="Materials" items={Object.values(materialClusters)} path={(i)=>`/materials/${i.slug}`} label={(i)=>i.title}/><Section title="Trust Guides" items={Object.values(trustClusters)} path={(i)=>`/trust/${i.slug}`} label={(i)=>i.title}/><Section title="Comparisons" items={Object.values(comparisonClusters)} path={(i)=>`/comparisons/${i.slug}`} label={(i)=>i.title}/><Section title="Templates" items={Object.values(templateClusters)} path={(i)=>`/templates/${i.slug}`} label={(i)=>i.title}/></main></>}
