import { useRouter } from 'next/router';
import fs from 'fs';
import path from 'path';

export async function getStaticPaths() {
  try {
    // Read the file generated by your automated SEO agent python script
    const filePath = path.join(process.cwd(), 'seo_updates.json');
    const fileData = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(fileData);

    // Tell Next.js to prepare paths for every new competitor gap found
    const paths = data.optimized_data.suggested_routes.map((item) => ({
      params: { industry: item.route.replace('/qr-for-', '') },
    }));

    return { paths, fallback: 'blocking' };
  } catch (error) {
    // Fallback pages if the script hasn't run yet
    return {
      paths: [
        { params: { industry: 'kirana-stores' } },
        { params: { industry: 'taxi-drivers' } }
      ],
      fallback: 'blocking',
    };
  }
}

export async function getStaticProps({ params }) {
  const { industry } = params;
  let pageHeading = `Free UPI QR Code Generator for ${industry.replace('-', ' ')}`;
  let pageBody = "Accept digital payments directly into your bank account with zero merchant transactional fees.";

  try {
    const filePath = path.join(process.cwd(), 'seo_updates.json');
    const fileData = fs.readFileSync(filePath, 'utf8');
    const data = JSON.parse(fileData);

    const matchedRoute = data.optimized_data.suggested_routes.find(
      (r) => r.route === `/qr-for-${industry}`
    );

    if (matchedRoute) {
      pageHeading = matchedRoute.heading;
      pageBody = matchedRoute.body_text;
    }
  } catch (e) {}

  return {
    props: { pageHeading, pageBody },
    revalidate: 86400, // Refresh page once a day
  };
}

export default function ProgrammaticPage({ pageHeading, pageBody }) {
  return (
    <main className="min-h-screen flex flex-col items-center justify-center p-8 bg-slate-50 text-slate-900 font-sans">
      <div className="text-center max-w-2xl mb-8">
        <span className="text-xs font-bold tracking-widest text-emerald-600 uppercase bg-emerald-50 px-3 py-1 rounded-full">
          0% MDR Autopilot Feature
        </span>
        <h1 className="text-4xl font-extrabold tracking-tight mt-3 mb-4 capitalize">
          {pageHeading}
        </h1>
        <p className="text-lg text-slate-600">
          {pageBody}
        </p>
      </div>
      <div className="mt-6 text-center text-xs text-slate-400 bg-white border p-4 rounded-xl shadow-sm max-w-md">
        🛡️ Secure instant settlement supported across 140+ Indian banking apps including GPay, PhonePe, and Paytm.
      </div>
    </main>
  );
}
