import Head from 'next/head';
import Link from 'next/link';
import materialClusters from '../../data/material_clusters.json';
import toolClusters from '../../data/tool_clusters.json';

export async function getStaticPaths(){ return { paths: Object.values(materialClusters).map(i=>({params:{slug:i.slug}})), fallback:false }; }export async function getStaticProps({params}){ const item=Object.values(materialClusters).find(i=>i.slug===params.slug); if(!item) return {notFound:true}; return {props:{item}, revalidate:86400}; }

export default function MaterialPage({item}){
  const url=`https://bharathqr.com/materials/${item.slug}`;
  const tools=(item.tools||[]).map(k=>toolClusters[k]).filter(Boolean);
  const desc=`${item.primary_keyword}: best QR tools, print tips, placement ideas and mistakes to avoid for Indian businesses.`;
  const schema={'@context':'https://schema.org','@type':'WebPage',name:item.title,description:desc,url};
  return <><Head><title>{item.title} — BharathQR</title><meta name="description" content={desc.slice(0,155)}/><link rel="canonical" href={url}/><meta property="og:title" content={`${item.title} — BharathQR`}/><meta property="og:description" content={desc.slice(0,155)}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></Head><main style={{maxWidth:1000,margin:'0 auto',padding:'1.5rem 1rem'}}><section style={{background:'linear-gradient(135deg,#ECFDF5,#FFFFFF)',border:'1px solid #D1FAE5',borderRadius:24,padding:'clamp(1.25rem,5vw,2.5rem)',textAlign:'center'}}><p style={{color:'#1D9E75',fontWeight:800,margin:0}}>Print + QR Use Case</p><h1 style={{fontSize:'clamp(2rem,7vw,3.2rem)',margin:'0.5rem 0'}}>{item.title}</h1><p style={{color:'#4B5563',fontSize:18,lineHeight:1.6}}>{item.primary_keyword} helps businesses turn printed material into payments, WhatsApp enquiries, Google reviews, menus and website visits.</p></section><section style={{marginTop:28,display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(250px,1fr))',gap:16}}><div style={{border:'1px solid #E5E7EB',borderRadius:18,padding:20}}><h2>Pain points solved</h2><ul>{item.pain_points.map(p=><li key={p}>{p}</li>)}</ul></div><div style={{border:'1px solid #E5E7EB',borderRadius:18,padding:20}}><h2>Benefits</h2><ul>{item.benefits.map(b=><li key={b}>{b}</li>)}</ul></div></section><section style={{marginTop:28}}><h2>Best BharathQR tools for {item.primary_keyword}</h2><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:14}}>{tools.map(t=><Link key={t.slug} href={t.tool_url} style={{border:'1px solid #D1FAE5',borderRadius:16,padding:18,textDecoration:'none',color:'#111827',background:'#F0FDF4'}}><strong style={{color:'#065F46'}}>{t.title}</strong><p style={{color:'#4B5563'}}>{t.primary_keyword} for print and business use.</p><span style={{color:'#1D9E75',fontWeight:800}}>Open tool →</span></Link>)}</div></section><section style={{marginTop:28,lineHeight:1.7}}><h2>Print tips</h2><ul>{item.print_tips.map(t=><li key={t}>{t}</li>)}</ul><h2>Mistakes to avoid</h2><ul><li>Do not print tiny QR codes that customers cannot scan.</li><li>Do not place QR codes on folds, glossy glare or curved surfaces without testing.</li><li>Do not forget to add a clear CTA such as Scan to Pay, Scan Menu or Scan on WhatsApp.</li></ul><h2>FAQ</h2><h3>Can I use BharathQR for {item.primary_keyword.toLowerCase()}?</h3><p>Yes. Generate the QR, download the PNG, test it on your phone and then print it on your material.</p><h3>Which QR is best?</h3><p>Use URL QR for websites, WhatsApp QR for enquiries, UPI QR for payments, Google Review QR for reviews and vCard QR for contact saving.</p></section></main></>;
}
